#!/bin/bash

	for student in $(cat /root/inputfiles/cleanstudentDetails.txt)
	do
	#	echo -e  $student
	#	sleep 2
	Name="$(echo -e  $student | awk -F:  '{print $1}')"
	RollNumber="$(echo -e  $student | awk -F:  '{print $2}')"
	Hostel="$(echo -e  $student | awk -F:  '{print $3}')"
	Room="$(echo -e  $student | awk -F:  '{print $4}')"
	Mess="$(echo -e  $student | awk -F:  '{print $5}')"
	MessPref="$(echo -e  $student | awk -F:  '{print $6}')"
#	# Check if student is already exist in System 
		echo -e " Setting Permission for user : " $Name
		sudo chmod 660  /home/$Hostel/$Room/$Name/* 2>/dev/null
		sudo chmod 600  /home/$Hostel/$Room/$Name/.bashrc 2>/dev/null
		sudo chmod 777  /home/$Hostel/$Room/$Name/messallocation4students 2>/dev/null
		sudo chmod 777  /home/$Hostel/$Room/$Name/feeBreakup 2>/dev/null
	done  
